version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8080"
    restart: unless-stopped

  caddy:
    image: caddy:latest
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    command: >
      sh -c "
        apk add --no-cache openssl &&
        mkdir -p /data &&
        openssl req -x509 -newkey rsa:4096 -keyout /data/key.pem -out /data/cert.pem -days 365 -nodes -subj '/CN=localhost' &&
        caddy run --config /etc/caddy/Caddyfile
      "
    depends_on:
      - api
    restart: unless-stopped